# Server Port (Product Service එක 8081 නිසා මෙයට 8082 ලබා දිය යුතුයි)
server.port=8084

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/ecommerce_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
